# Generated by Django 5.0.2 on 2024-02-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="course_id",
            new_name="course_code",
        ),
    ]
